apiVersion: v1
kind: Pod
metadata:
  name: pod-lab6
spec:
  volumes:
    - name: pv-storage-lab6
      persistentVolumeClaim:
        claimName: pv-claim-lab6
  containers:
    - name: pv-container-lab6
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/www"
          name: pv-storage-lab6