# Command to create secrets:
# kubectl create secret generic mysql --from-literal=password=root
apiVersion: v1
kind: Pod
metadata:
  name: mymysql
  namespace: default
spec:
  containers:
    - name: fake-mysql
      image: busybox
      command:
        - "sleep"
        - "3600"
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password