# Command to create secrets:
# kubectl create secret generic secretstuff --from-literal=password=password --from-literal=user=linda
apiVersion: v1
kind: Pod
metadata:
  name: secrectbox2
  namespace: default
spec:
  containers:
  - name: secretbox
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /secretstuff
        name:  secret
  volumes:
    - name: secret
      secret:
        secretName: secretstuff